spring:
  cloud:
    gateway:
      routes:
        - id: order-rote
          uri: lb://server-order
          predicates:
            - name: Path
              args:
                patterns: /order/**
          order: 1
        - id: product-rote
          uri: lb://server-product
          predicates:
            - Path=/product/**
          order: 2