spring:
  cloud:
    gateway:
      routes:
        - id: order-rote
          uri: lb://server-order
          predicates:
            - Path=/order/**
        - id: product-rote
          uri: lb://server-product
          predicates:
            - Path=/product/**
