spring:
  application:
    name: seata-order
  cloud:
    inetutils:
      useOnlySiteLocalInterfaces: true
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false

server:
  port: 12000
